### ISSUE TITLE
Running as Azure Function

### ISSUE THREAD

**Issue by lukju** [Luminis-Arnhem/AzureStorageBackup#7]
Hi! I tried your awesome backup package but unfortunately, wasn't able to run it in an Azure Function. I get:

2021-04-12T13:05:32.852 [Error] Executed 'StorageBackupTimerJob' (Failed, Id=56b7ee54-e3f1-4ac5-868a-c886342e5106, Duration=159ms)AzCopy.exe not found in D:\Program Files (x86)\SiteExtensions\Functions\3.0.15417\32bit

According you blog post https://www.luminis.eu/blog/backup-azure-storage-using-azure-functions-in-3-easy-steps/ you also deployed it as Azure Function. How have you been successful?

**Comment by lukju** [comment]
Got it. Sorry...

**Comment by srksenthilkumar** [comment]
> Got it. Sorry...

I am also facing the same issue, how did you solve this issue.

**Comment by srksenthilkumar** [comment]
> Got it. Sorry...

I am also facing the same issue. When I publish it to Azure Function App, It creates the "azcopy" folder in "wwwroot" which has only "azcopy.exe" file. Another "azcopy" folder got created in "wwwroot\bin" which has all the DLL files.

Because of this AzCopy command is unable to find "Microsoft.WindowsAzure.Storage.dll" and its method.

Any clue what I am missing here. Thanks.
